### ISSUE TITLE
Planning on PPA?

### ISSUE THREAD

**Issue by natrius** [TheAxelander/OpenBudgeteer#100]
Do you have any plans on release it as PPA? Or is it just Docker or installing with .net? 

And, what i'm simply curious about: if it has nothing to do with Windows basically - why is there a need to install .net? :) Sorry, no dev.

**Comment by TheAxelander** [comment]
Currently it is not planned from my side making OpenBudgeteer available as PPA.

Why .Net? Simple answer, I used C# for most of the time and this is where I have most of my experience compared to other languages and frameworks. Also .Net is longer only purely for Windows, it's maybe not that famous on Linux based environments like Python or others, but it's also not dedicated to Windows based systems any longer.

**Comment by csillaggyujto** [comment]
Hard, but not impossible. The repository is built in C#.NET, because.... we're .NET devs. .NET is now an open-source cross-platform project, and you should think about it as something like Java (history says, .NET was meant to be Microsoft Java after all) - a build once, run anywhere VM platform. Since it's now possible to compile AOT, we can explore building against dotnet-deps (ca-certificates, libc6, libgcc, libssl3, libstdc++6, and zlib1g) on Alpine for the Dockerized version, and this will make the .deb archive possible - complete with the systemd unit to run it. (I hope Ubuntu is still systemd, debian and mint is.)

The self-contained deployment would probably be large - the compiler would have to include half the .net runtime. Also, after the login support, and the api support, maybe we will have to fork - the architecture as I can see it isn't meant to be a monolithic, desktop-like app, but a microservices-based web application meant to integrate with what self-hosters have at home. And if you host any of the *arr's, you have .net installed - they are .net projects, also!

But keeping this in mind, we either keep the FE and the BE together, or package as two different applications, which you can pull, so you can deploy the BE separately from the FE, all from apt.
