### ISSUE TITLE
Import not possible

### ISSUE THREAD

**Issue by Serph91P** [TheAxelander/OpenBudgeteer#161]
Hi,

already looked at other issues. but nothing seems to be applicable to me.
When I try to import my csv file. I setup the import profile which is working fine in regards to the columns.
I set No special settings for Debit and Credit, because there are none as far as I am aware.
When I get to Validate all entries get errors "Column 7 with Value '-9,13 €' cannot be converted" like this.
When I set "Credit values are in separate columns" to the same where the "Amount / Debit:" is set I could Import but all Amounts are 0.
Language is set to de-DE

**Comment by TheAxelander** [comment]
Hi,

I think the issue is that the column contains the currency symbol. Based on your explanation this would be the right setting:

![image](https://github.com/TheAxelander/OpenBudgeteer/assets/17849665/5ec6f066-cf1b-4511-943f-cff3628c9fbc)

The next "challenge", I think you are using DKB isn't it? 

It is important to copy & past the substring " €" from the original CSV file into the field `Characters / Substring to be removed:` Entering it manually doesn't work for some reason. Either it's Euro symbol or they are using a non-standard space character. 

I also had the same issue, just crazy...

**Comment by Serph91P** [comment]
> Hi,
> 
> I think the issue is that the column contains the currency symbol. Based on your explanation this would be the right setting:
> 
> ![image](https://user-images.githubusercontent.com/17849665/258040732-5ec6f066-cf1b-4511-943f-cff3628c9fbc.png)
> 
> The next "challenge", I think you are using DKB isn't it?
> 
> It is important to copy & past the substring " €" from the original CSV file into the field `Characters / Substring to be removed:` Entering it manually doesn't work for some reason. Either it's Euro symbol or they are using a non-standard space character.
> 
> I also had the same issue, just crazy...

Thank you so much for the fast reply.

Yep That worked. I had entered the € symbol before but it did not work. This is indeed very strange that you have to copy exact from the file.
