### ISSUE TITLE
[pre-release] Potential long runtime on Data Consistency checks

### ISSUE THREAD

**Issue by TheAxelander** [TheAxelander/OpenBudgeteer#271]
**Describe the bug**
It looms like that for some reason the Data Consistency checks have some heavy run time compared to latest stable version with the same amount of data.

**Comment by TheAxelander** [comment]
Bottleneck CPU of Database

Pre-release:
2 Cores: 1:55
4 Cored: 0:52

Latest:
2 Cores: 0:02 (with data until May 2024)

Potentially new Repository & Services setup is the root cause here (Querying too much data)

**Comment by Lucaber** [comment]
https://github.com/TheAxelander/OpenBudgeteer/blob/4e793f68ed748a30d29c2d8e54d3b0cf3a3653f2/OpenBudgeteer.Core.Data.Services/Generic/GenericBudgetedTransactionService.cs#L32-L41

The `Where` clause in the `GetAllFromTransaction` method gets evaluated on the client instead of being sent as part of the sql query. The reason seems to be the return type `IEnumerable<BudgetedTransaction>` of the `AllWithTransactions()` method. A quick test by casting the result back to an `IQueryable<BudgetedTransaction>` speeds loading times 20x.

```csharp
        return (_budgetedTransactionRepository
            .AllWithTransactions() as IQueryable<BudgetedTransaction>)
            .Where(i =>
                i.Transaction.TransactionDate >= periodStart &&
                i.Transaction.TransactionDate <= periodEnd &&
                i.TransactionId == transactionId)
            .ToList();
```

**Comment by TheAxelander** [comment]
Yeah that is most likely the root cause (potentially across all queries). I need to have a look on the query logs how EF is generating the SQL after the latest changes. 

I remember when I have set up the Repositories I was also playing around with `IQueryable<T>` but for some reason I ended up with `IEnumerable<T>` which was working as expected at that time. I need to understand now why all of the sudden this behavior occurs.
