### ISSUE TITLE
Mobile friendly creation of transactions

### ISSUE THREAD

**Issue by tizzen33** [TheAxelander/OpenBudgeteer#275]
Hello again, 
I'm using the app to keep track of my budget on a daily basis and I enter all my transactions manually at the end of the day. I have to do this on my large screen because not all buttons and fields are visible on my mobile. 
Any improvement foreseen on that? A separate view perhaps with all input fields below each other.
Or I could use the API and create a separate page but I can't find any docs for the API.

Thanks
Tijs

**Comment by TheAxelander** [comment]
Hi Tijs,

you can spin up an API Container to interact with the database via API. See [here](https://theaxelander.github.io/latest/install/#docker-compose-recommended) for more details. The container also contains the documentation which is accessible via WebUI on the mapped port based on your Docker compose.

Mobile accessibility I tried to make it useable as good as possible, but only from viewing perspective and not for modifying/creating things like Transactions or Buckets. Because at a certain point of time you simply run out of space to make it usable from my point of view.

**Comment by tizzen33** [comment]
Thanks for the clarification, I understand. 

About the API, I already started the container and the WebUI is accessible on the mapped port but it's empty...

Docker logs show:

> info: Microsoft.Hosting.Lifetime[14]
>       Now listening on: http://[::]:8080
> info: Microsoft.Hosting.Lifetime[0]
>       Application started. Press Ctrl+C to shut down.
> info: Microsoft.Hosting.Lifetime[0]
>       Hosting environment: Production
> info: Microsoft.Hosting.Lifetime[0]
>       Content root path: /api
>

**Comment by TheAxelander** [comment]
What do mean with empty? Do you see the Swagger page?

Edit: Ah, maybe I think you need to add /api in the browser to access it.

**Comment by tizzen33** [comment]
Connection to the port is not refused but 404 error on both / and /api

**Comment by TheAxelander** [comment]
Hhm, strange. I can test this on the weekend earliest, once I'm back home...

**Comment by tizzen33** [comment]
Yes, sure, no problem. Same issue on pre-release version, not sure what I'm doing wrong. Same environment variables for both containers.

**Comment by tizzen33** [comment]
Hi, sorry to bother you. I retried a few times but can't get it to work. Without the right database details, the container doesn't start. So that's not the issue.

**Comment by TheAxelander** [comment]
Sorry for the late response. I see a gap in my documentation to clearly point out where to access the Swagger UI. Can you try to check if the `/swagger` endpoint works for you.

**Comment by tizzen33** [comment]
Aha that's it! Thanks a lot.
