### ISSUE TITLE
Recurring Transactions

### ISSUE THREAD

**Issue by josolanes** [TheAxelander/OpenBudgeteer#74]
I'd like to see recurring transactions added (monthly, weekly, bi-weekly, annually, etc) to make managing regularly occurring bills more or less automated

**Comment by TheAxelander** [comment]
Just to understand your use case better:

Instead of importing a bunch of transactions (which then also contains recurring postings) you enter them manually. To simplify this the goal is to automate the creation of recurring transactions.

Is this interpretation correct or what is the overall background of having automated generation of transactions?

**Comment by natrius** [comment]
Yes, its interesting for that usecase. An automatic importer for my bank is basically not possible, so i would have to enter everything manually anyway. Plus, there are people who are going to sit down and enter everything manually so they have an eye on everything faster.

**Comment by TheAxelander** [comment]
Got the point. I will work on that for the next version

**Comment by josolanes** [comment]
Thanks @TheAxelander ! As @natrius  mentioned, I fall into the category who prefers maintaining it all within software directly instead of importing CSVs. I think managing recurring transactions would be easier than importing CSVs, and allows me to be more aware of what's going on

**Comment by TheAxelander** [comment]
Hey all,

I didn't had much time in the past months to work on it, but now it is available in `pre-release`
