### ISSUE TITLE
Recurring transactions and budget edit options

### ISSUE THREAD

**Issue by Sasillo** [TheAxelander/OpenBudgeteer#91]
Hello The Alexander, 

First of all, excellent project, I'm currently trying to migrate all my YNBA data manually, but i miss the option of create a recurrent transaction ( weekly, monthly, yearly... ), I think this is a basic one and not so dificult to implement. :)

I like the opcion of "Distribute budget", it could be nice have the option of "clear all" too once assigned, and an option to "clear" just some selected budget groups, or categories, now the only way to edit it is editing directly the database, that is slower and dificult.

Thanks for this deploy. I really like the software.

Regards,

**Comment by TheAxelander** [comment]
Hi Sasillo,

thank you very much for your feedback.

Recurrent transaction is already covered by #74 

Regarding "clear all": You can always remove budget out of buckets by entering negative numbers in the InOut field. This also the safest way instead of manipulating the database as this could lead to data inconsistencies.
